apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-config
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  cdnIdTemplate: {{ .Values.screenshotConfig.cdnIdTemplate | quote }}
  cdnUrlTemplate: {{ .Values.screenshotConfig.cdnUrlTemplate | quote }}
  cdnPrefixTemplate: {{ .Values.screenshotConfig.cdnPrefixTemplate | quote }}
  outDir: {{ .Values.screenshotConfig.outDir | quote }}
  titles: {{ "\"" }}
    {{- range $key, $val := .Values.screenshotConfig.urls }}
    {{- $key }},
    {{- end }}
    {{- "\"" }}
  urls: {{ "\"" }}
    {{- range $key, $val := .Values.screenshotConfig.urls }}
    {{- $val }},
    {{- end }}
    {{- "\"" }}
  sizes: {{ "\"" }}
    {{- range $key, $val := .Values.screenshotConfig.sizes }}
    {{- $key }}:
    {{- $val }},
    {{- end }}
    {{- "\"" }}