replicaCount: 1
image: schemes-screenshots:latest
pullPolicy: IfNotPresent
service:
  name: schemes-screenshots
  type: NodePort
  externalPort: 80
  internalPort: 5000
secrets:
  cloudinaryUrl: "base64 encoded 'cloudinary://clientId:clientSecrete@cloudName'"
screenshotUrls:
  Google Search: https://www.google.com/search?hl=en&q={colorSchemeName}
  Google Search Images: https://www.google.com/search?hl=en&tbm=isch&q={colorSchemeName}
  Wikipedia: https://en.wikipedia.org/wiki/Orion_Nebula
screenshotCdnIdTemplate: cs/{id}/{title}/{size}
env:
  ASPNETCORE_URLS: http://*:5000
  CHROME_EXECUTABLE_PATH: /usr/bin/google-chrome-unstable
  CHROME_KILL_EXISTING_PROCESSES: google-chrome-unstable
  CHROME_FLAGS: --disable-gpu
  EXTENSION_DOWNLOAD_URL: https://github.com/Midnight-Lizard/Midnight-Lizard/releases/download/latest/chrome.zip
  EXTENSION_ARCHIVE_PATH: ./ext/ml
  EXTENSION_EXTRACT_PATH: ./ext/ml.zip
  EXTENSION_DEFAULT_COLOR_SCHEME_ID: dimmedDust
  SCREENSHOT_OUT_DIR: ./img
  SCREENSHOT_SIZES: 1280x800x200,1120x700x200,960x600x200,800x500x200,640x400x200
  SCREENSHOT_CDN_PREFIX_TEMPLATE: cs/{id}
  SCHEMES_EVENTS_TOPIC: schemes-events-a
  KAFKA_EVENTS_CONSUMER_CONFIG: |-
    {
      "group.id": "schemes-screenshots-generator",
      "bootstrap.servers": "bootstrap.kafka:9092",
      "partition.assignment.strategy": "range",
      "enable.auto.commit": false,
      "auto.commit.interval.ms": 1000,
      "auto.offset.reset": "earliest"
    }