replicaCount: 1
image: schemes-screenshots:latest
pullPolicy: IfNotPresent
livenessProbe:
  path: /status/isalive
  initialDelaySeconds: 60
  periodSeconds: 45
  timeoutSeconds: 10
readinessProbe:
  path: /status/isready
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
service:
  name: schemes-screenshots
  type: NodePort
  externalPort: 80
  internalPort: 5000
secrets:
  cloudinaryUrl: "base64 encoded 'cloudinary://clientId:clientSecrete@cloudName'"
screenshotConfig:
  outDir: ./img
  cdnIdTemplate: cs/{id}/{title}/{size}
  cdnUrlTemplate: https://res.cloudinary.com/midnight-lizard/{id}.jpg
  cdnPrefixTemplate: cs/{id}/
  sizes:
    xl: 1280x800x200
    lg: 1120x700x200
    md: 960x600x200
    sm: 800x500x200
    xs: 640x400x200
  urls:
    # Google Search: https://www.google.com/search?hl=en&q={colorSchemeName}
    Wikipedia: https://en.wikipedia.org/wiki/Orion_Nebula
    DuckDuckGo: https://duckduckgo.com/?t=h_&ia=web&kp=1&q={colorSchemeName}
    DuckDuckGo Images: https://duckduckgo.com/?t=h_&iar=images&iax=images&ia=images&kp=1&q={colorSchemeName}
    Medium: https://medium.com
    # Google Search Images: https://www.google.com/search?hl=en&tbm=isch&q={colorSchemeName}
env:
  ASPNETCORE_URLS: http://*:5000
  CHROME_EXECUTABLE_PATH: /usr/bin/google-chrome-stable
  CHROME_KILL_EXISTING_PROCESSES: google-chrome-stable
  CHROME_FLAGS: --disable-gpu
  EXTENSION_DOWNLOAD_URL: https://github.com/Midnight-Lizard/Midnight-Lizard/releases/download/latest/chrome.zip
  EXTENSION_ARCHIVE_PATH: ./ext/ml
  EXTENSION_EXTRACT_PATH: ./ext/ml.zip
  EXTENSION_DEFAULT_COLOR_SCHEME_ID: dimmedDust
  SCHEMES_EVENTS_TOPIC: schemes-events-a
  KAFKA_EVENTS_CONSUMER_CONFIG: |-
    {
      "group.id": "schemes-screenshots-generator",
      "bootstrap.servers": "bootstrap.kafka:9092",
      "partition.assignment.strategy": "range",
      "enable.auto.commit": false,
      "auto.commit.interval.ms": 1000,
      "auto.offset.reset": "earliest"
    }